# Generated by Django 4.2 on 2023-09-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
