# Generated by Django 4.2 on 2023-10-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_complaint_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='sender_number',
            field=models.CharField(max_length=50),
        ),
    ]
