# Generated by Django 4.2 on 2023-09-15 07:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='blogPost'),
        ),
    ]
