# Generated by Django 4.2 on 2023-09-24 17:54

import datetime
from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlog',
            name='complaint_text',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='customerlog',
            name='possible_solution',
            field=froala_editor.fields.FroalaField(default=datetime.datetime(2023, 9, 24, 17, 54, 22, 229409, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
